# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'den_uty.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_step1_txt = QtWidgets.QLabel(self.centralwidget)
        self.label_step1_txt.setObjectName("label_step1_txt")
        self.verticalLayout.addWidget(self.label_step1_txt)
        self.pushButton_step1_inputdir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_step1_inputdir.setObjectName("pushButton_step1_inputdir")
        self.verticalLayout.addWidget(self.pushButton_step1_inputdir)
        self.label_step1_inputPath = QtWidgets.QLabel(self.centralwidget)
        self.label_step1_inputPath.setObjectName("label_step1_inputPath")
        self.verticalLayout.addWidget(self.label_step1_inputPath)
        self.label_step2_txt = QtWidgets.QLabel(self.centralwidget)
        self.label_step2_txt.setObjectName("label_step2_txt")
        self.verticalLayout.addWidget(self.label_step2_txt)
        self.pushButton_step2_weightdir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_step2_weightdir.setObjectName("pushButton_step2_weightdir")
        self.verticalLayout.addWidget(self.pushButton_step2_weightdir)
        self.label_step2_path = QtWidgets.QLabel(self.centralwidget)
        self.label_step2_path.setObjectName("label_step2_path")
        self.verticalLayout.addWidget(self.label_step2_path)
        self.label_step3_txt = QtWidgets.QLabel(self.centralwidget)
        self.label_step3_txt.setObjectName("label_step3_txt")
        self.verticalLayout.addWidget(self.label_step3_txt)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider_step3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_step3.setProperty("value", 20)
        self.horizontalSlider_step3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_step3.setObjectName("horizontalSlider_step3")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_step3)
        self.label_step3_val = QtWidgets.QLabel(self.centralwidget)
        self.label_step3_val.setObjectName("label_step3_val")
        self.horizontalLayout_2.addWidget(self.label_step3_val)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_step3_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_step3_reset.setObjectName("pushButton_step3_reset")
        self.verticalLayout.addWidget(self.pushButton_step3_reset)
        self.label_step4_txt = QtWidgets.QLabel(self.centralwidget)
        self.label_step4_txt.setObjectName("label_step4_txt")
        self.verticalLayout.addWidget(self.label_step4_txt)
        self.pushButton_step4_outputdir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_step4_outputdir.setObjectName("pushButton_step4_outputdir")
        self.verticalLayout.addWidget(self.pushButton_step4_outputdir)
        self.label_step4_outputdir = QtWidgets.QLabel(self.centralwidget)
        self.label_step4_outputdir.setObjectName("label_step4_outputdir")
        self.verticalLayout.addWidget(self.label_step4_outputdir)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_clearall = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clearall.setObjectName("pushButton_clearall")
        self.horizontalLayout_3.addWidget(self.pushButton_clearall)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_doProcess = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_doProcess.setEnabled(False)
        self.pushButton_doProcess.setObjectName("pushButton_doProcess")
        self.horizontalLayout_3.addWidget(self.pushButton_doProcess)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_step1_txt.setText(_translate("MainWindow", "1. Input Image Directory"))
        self.pushButton_step1_inputdir.setText(_translate("MainWindow", "Select"))
        self.label_step1_inputPath.setText(_translate("MainWindow", "path here"))
        self.label_step2_txt.setText(_translate("MainWindow", "2. prompt weight file"))
        self.pushButton_step2_weightdir.setText(_translate("MainWindow", "Select"))
        self.label_step2_path.setText(_translate("MainWindow", "path here"))
        self.label_step3_txt.setText(_translate("MainWindow", "3. Test gaussian noise STDEV"))
        self.label_step3_val.setText(_translate("MainWindow", "val"))
        self.pushButton_step3_reset.setText(_translate("MainWindow", "Default"))
        self.label_step4_txt.setText(_translate("MainWindow", "4.Output Image Directory"))
        self.pushButton_step4_outputdir.setText(_translate("MainWindow", "Select"))
        self.label_step4_outputdir.setText(_translate("MainWindow", "path here"))
        self.label_status.setText(_translate("MainWindow", "Status:Idel, waiting for user prompting parameters."))
        self.pushButton_clearall.setText(_translate("MainWindow", "Clear All"))
        self.pushButton_doProcess.setText(_translate("MainWindow", "Process Denoising"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

